### ISSUE TITLE
Sugar Dusted Coal

### ISSUE THREAD

**Issue by Timelord-10** [Shnupbups/Sweet-Tooth#4]
Sugar Dusted Coal did not register as fuel. It could not be accepted into the input slot of the smoker or furnace.

**Comment by fatlard1993** [comment]
I've created a PR that fixes this

**Comment by DanShu15** [comment]
Seems this issue has cropped back up again for both coal and charcoal. They can't be placed in the fuel slot of vanilla or modded furnaces. Not sure about the smoker tho

**Comment by fatlard1993** [comment]
To my knowledge there was never a build posted that contained my fix. On my server I am using the copy I built

**Comment by DanShu15** [comment]
well RIP lol

**Comment by fatlard1993** [comment]
just clone the repo and build it .. super quick and easy
