### ISSUE TITLE
Crash when I launch the game.

### ISSUE THREAD

**Issue by Nero2137** [Shnupbups/Sweet-Tooth#6]
Crash-report:
[crash-2020-01-10_19.43.18-client.txt](https://github.com/Shnupbups/Sweet-Tooth/files/4046982/crash-2020-01-10_19.43.18-client.txt)

**Comment by Shnupbups** [comment]
Do you have Fabric API installed? Get it here: https://www.curseforge.com/minecraft/mc-mods/fabric-api

**Comment by Nero2137** [comment]
I have Fabric API, because it need for other mods.
